AWSTemplateFormatVersion: 2010-09-09
Description: A-New-Startup - ECS - Creates a-new-startup Service for the ECS Cluster.  Assume the ALB was already created (for speed)

Parameters:
  
  ImageURI:
    Type: String
    Default: 123456789012.dkr.ecr.region.amazonaws.com/image:tag

  ServiceName:
    Type: String
    # update with the name of the service
    Default: a-new-startup

  ContainerPort:
    Type: Number
    Default: 3000
  
  HealthCheckPath:
    Type: String
    Default: /
    
Resources:

  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Join ['-', [/ecs/, !Ref ServiceName, TaskDefinition]]

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    DependsOn: LogGroup
    Properties:
      Family: 'a-new-startup'
    
      # awsvpc required for Fargate
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      Cpu: 256
      Memory: 0.5GB
      
      ExecutionRoleArn: !ImportValue ecs-demo-ExecutionRole
      TaskRoleArn: !ImportValue ecs-demo-TaskRole
      
      ContainerDefinitions:
        - Name: !Ref ServiceName
          Image: !Ref ImageURI
          PortMappings:
            - ContainerPort: !Ref ContainerPort
          # The code expects to find these environment variables.
          Environment:
            - Name: APP_TABLE_NAME
              Value: a-new-startup-dev
            - Name: APP_TOPIC_ARN
              Value: 
                Fn::Join:
                  - ""
                  - - "arn:"
                    - Ref: AWS::Partition
                    - ":sns:"
                    - Ref: AWS::Region
                    - ":"
                    - Ref: AWS::AccountId
                    - ":a-new-startup-dev"
          # Send logs to CloudWatch Logs
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-region: !Ref AWS::Region
              awslogs-group: !Ref LogGroup
              awslogs-stream-prefix: ecs
  
  ContainerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Join ['', [!Ref ServiceName, ContainerSecurityGroup]]
      VpcId: !ImportValue ecs-demo-VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: !Ref ContainerPort
          ToPort: !Ref ContainerPort
          SourceSecurityGroupId: !ImportValue ecs-demo-LoadBalancerSecurityGroup
  
  Service:
    Type: AWS::ECS::Service
    # Need to make sure the ALB is ready first.
    DependsOn:
      - ListenerHTTPS
    Properties: 
      ServiceName: !Ref ServiceName
      Cluster: !ImportValue ecs-demo-Cluster
      TaskDefinition: !Ref TaskDefinition
      DeploymentController:
        # ECS is in control - NOT CODE_DEPLOY
        Type: ECS
      DeploymentConfiguration:
        MinimumHealthyPercent: 100
        MaximumPercent: 200
      DesiredCount: 2
      HealthCheckGracePeriodSeconds: 30
      LaunchType: FARGATE
      NetworkConfiguration: 
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          # Running Fargate in PUBLIC subnets.  (OK on ECS, Not OK on EKS)
          Subnets: !Split [',', !ImportValue ecs-demo-PublicSubnets]
          SecurityGroups:
            - !Ref ContainerSecurityGroup
      LoadBalancers:
        - ContainerName: !Ref ServiceName
          ContainerPort: !Ref ContainerPort
          TargetGroupArn: !Ref TargetGroup
  
  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckIntervalSeconds: 10
      HealthCheckPath: !Ref HealthCheckPath
      HealthCheckTimeoutSeconds: 5
      UnhealthyThresholdCount: 2
      HealthyThresholdCount: 2
      Name: !Join ['-', [!Ref ServiceName, TargetGroup]]
      Port: !Ref ContainerPort
      Protocol: HTTP
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: 20 # Make it short for faster demos.
      TargetType: ip
      VpcId: !ImportValue ecs-demo-VpcId

  
  ListenerHTTPS:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - TargetGroupArn: !Ref TargetGroup
          Type: forward
      LoadBalancerArn: !ImportValue ecs-demo-LoadBalancer
      Port: !ImportValue ecs-demo-LoadBalancerPort
      Protocol: HTTP

Outputs:
  
  TaskDefinition:
    Value: !Ref TaskDefinition
    Export:
      Name: "ecs-demo-TaskDefinition"